###
GET http://localhost:3000/api/categories/

###
POST http://localhost:3000/api/categories
Content-Type: application/json

{
    "description": "Carrito Bar"
}


###
GET http://localhost:3000/api/categories/62a7bd70a31da5baf7b6bc23


###
PUT http://localhost:3000/api/categories/62a7b86880f90694064a1794
Content-Type: application/json

{
    "idCategoryParent": "62a3ba15b95f6344b83e7caf"
}

###
DELETE http://localhost:3000/api/categories/62bcf631202c3b45cec5407e

