###
GET http://localhost:3000/api/categories/

###
POST http://localhost:3000/api/categories
Content-Type: application/json

{
    "description": "Gastronomía",
    "idCategoryParent": "http3542"
}


###
GET http://localhost:3000/api/categories/62a3ba15b95f6344b83e7caf


###
PUT http://localhost:3000/api/categories/62a3ba15b95f6344b83e7caf
Content-Type: application/json

{
    "description": "Gastronomía"
}
