GET http://localhost:3000/api/stores/

###
POST http://localhost:3000/api/stores
Content-Type: application/json

{
    "name": "Malibu",
    "username": "sadfasdfasdf",
    "description": "gdfsgsdfgni",
    "address": "Chacabufdsgsdfg9",
    "city": "Rufino",
    "isService": false,
    "valoration": 5.0,
    "idCategory": "62b3a9171c3ecb4df2fbd673",
    "user": "62b3a9b71c3ecb4df2fbd67b"

}


###
GET http://localhost:3000/api/stores/62a750be4635495c180e406e

###
PUT http://localhost:3000/api/stores/62a750be4635495c180e406e
Content-Type: application/json

{
    "name": "The Vegan Soap"

}


###
DELETE http://localhost:3000/api/stores/62a750972471a77fc821f564

