GET http://localhost:3000/api/users/

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "email": "http3542@gmail.com",
    "username": "http3542",
    "password": "potato1",
    "firstname": "Potato",
    "lastname": "Chip",
    "birthDate": "",
    "phone": "11125253254"
}


###
GET http://localhost:3000/api/users/62a3b128ef5f61a7ca382897

###
PUT http://localhost:3000/api/users/62a3b128ef5f61a7ca382897
Content-Type: application/json

{
    "email": "chips@gmail.com",
    "username": "potatochip1"
}





























###
GET http://localhost:3000/api/categories/

###
POST http://localhost:3000/api/categories
Content-Type: application/json

{
    "description": "Gastronomía",
    "idCategoryParent": "http3542"
}


###
GET http://localhost:3000/api/categories/62a3ba15b95f6344b83e7caf


###
PUT http://localhost:3000/api/users/62a3ba15b95f6344b83e7caf
Content-Type: application/json

{
    "description": "Bares"
}
